### ISSUE TITLE
 File "C:\Users\31481\AppData\Local\Programs\Python\Python313\Lib\site-packages\qh3\quic\connection.py", line 566, in datagrams_to_send     crypto = self._cryptos[epoch]              ~~~~~~~~~~~~~^^^^^^^ KeyError: <Epoch.INITIAL: 0>

### ISSUE THREAD

**Issue by wangruiz** [iOSRealRun-cli/iOSRealRun-cli-17#69]

**Comment by Violiate** [comment]
哥们我也遇到这个问题了，你是怎么解决的？

**Comment by wangruiz** [comment]
> 哥们我也遇到这个问题了，你是怎么解决的？

你试试issue里有人发的iOS18吧，之前那个原作者不更新了

**Comment by Violiate** [comment]
好嘞，试过了已经，但是会被乐跑检测，跑完提示行为不规范在 2025年3月9日，20:07，crazy8dog ***@***.***> 写道：﻿
  
哥们我也遇到这个问题了，你是怎么解决的？

你试试issue里有人发的iOS18吧，之前那个原作者不更新了—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



crazy8dog left a comment (iOSRealRun/iOSRealRun-cli-17#69)

哥们我也遇到这个问题了，你是怎么解决的？

你试试issue里有人发的iOS18吧，之前那个原作者不更新了

**Comment by wangruiz** [comment]
> 好嘞，已经试过了，但是会被乐跑检测，跑提示行为不规范在 2025 年 3 月 9 日，20:07，crazy8dog ***@***.***> 写道：﻿哥们我也遇到这个问题了，你是解决的吗？评论过。消息ID：***@***.***>crazy8dog留下了一条评论（[iOSRealRun/iOSRealRun-cli-17#69](https://github.com/iOSRealRun/iOSRealRun-cli-17/issues/69)）哥们我也遇到了这个问题了，你是怎么解决的？你试试有人发的iOS18吧，那个原作者没有更新了——直接回复这封邮件，之前在GitHub上查看，或者取消订阅。你收到这个是因为你评论了。消息ID：***@***.***>

这个不清楚了，我们用的不是乐跑
